Psychtoolbox/PsychHardware/XOrgConfCreator.m
If `winfo.GLVersion` doesn't contain "Mesa", then `strfind` returns the empty vector and the statement throws an error.
=> XOrgConfCreator: wrap strfind call with isempty for non-Mesa setups

Psychtoolbox/PsychHardware/BitsPlusToolbox/BitsPlusTests/BitsPlusImagingPipelineTest.m
Config: Xubuntu 16.04 LTS, Quadro K620, NVIDIA driver 361.42, VPixx DATAPixx2, on NeuroDebian PTB-3: 3.0.12.20160514.dfsg1-1~nd16.04+1.
PsychGPUTestAndTweakGammaTables fails to find an identity clut mapping after 256 tweak iterations when run via BitsPlusImagingPipelineTest (selecting 'd' then 'y'). Visually, I see the luminance gradient briefly before it disappears into black, and then the script runs through each iteration reporting "765 mismatching pixels". So, I think each read consists solely of black pixels.
I do know that the type-III LUT is the proper mapping and requires no tweaks on this setup, but there may be some NVIDIA driver issue that needs a workaround.
I discovered three things to make this test work:
- Not skipping the sync tests (SkipSyncTests == 0) gives proper …
=> Strange interaction between DATAPixx2, NVIDIA 361, and IdentityClut

Psychtoolbox/PsychContributed/ple.m
In modern versions of MATLAB, errors are objects of type MException. I think s will always have a 'stack' property but to be on the safe side made the if statement check struct/object and field/prop.
=> Update ple.m to handle object stacks

PsychSourceGL/Source/Common/Base/MiniBox.c, PsychSourceGL/Source/Common/Base/PsychInit.c, PsychSourceGL/Source/Common/Base/PsychVersioning.c, PsychSourceGL/Source/Common/Screen/PsychGLGlue.c, PsychSourceGL/Source/Common/Screen/PsychGraphicsHardwareHALSupport.c, PsychSourceGL/Source/Common/Screen/PsychImagingPipelineSupport.c, PsychSourceGL/Source/Common/Screen/PsychMovieSupportGStreamer.c, PsychSourceGL/Source/Common/Screen/PsychMovieWritingSupportGStreamer.c, PsychSourceGL/Source/Common/Screen/PsychTextureSupport.c, PsychSourceGL/Source/Common/Screen/PsychVideoCaptureSupportGStreamer.c, PsychSourceGL/Source/Common/Screen/PsychVideoCaptureSupportLibDC1394.c, PsychSourceGL/Source/Common/Screen/PsychWindowSupport.c, PsychSourceGL/Source/Common/Screen/SCREENDrawDots.c, PsychSourceGL/Source/Common/Screen/SCREENDrawLines.c, PsychSourceGL/Source/Common/Screen/SCREENDrawText.c, PsychSourceGL/Source/Common/Screen/SCREENFillPoly.c, PsychSourceGL/Source/Common/Screen/SCREENGetFlipInfo.c, PsychSourceGL/Source/Common/Screen/SCREENGetImage.c, PsychSourceGL/Source/Common/Screen/SCREENGetMouseHelper.c, PsychSourceGL/Source/Common/Screen/SCREENNull.c, PsychSourceGL/Source/Common/Screen/SCREENResolutions.c, PsychSourceGL/Source/Common/Screen/SCREENTestTextureTwo.c, PsychSourceGL/Source/Common/Screen/SCREENTextFont.c, PsychSourceGL/Source/Common/Screen/ScreenTypes.c, PsychSourceGL/Source/Common/Screen/WindowHelpers.c, PsychSourceGL/Source/Linux/Base/PsychTimeGlue.c, PsychSourceGL/Source/Linux/Screen/PsychScreenGlue.c, PsychSourceGL/Source/Linux/Screen/PsychWindowGlue.c, PsychSourceGL/Source/Linux/Screen/PsychWindowTextGlue.c
Nothing ground breaking here.
You may have to take a look at the *GStreamer.c changes. Good news is that the "missing-field-initializers" warning for `GST_MAP_INFO_INIT` was fixed upstream. `videosinkCallbacks` had 4 function pointers in it, but `GstAppSinkCallbacks` defines 3 now, so I just culled the last of the one (which was a no-op).
=> Screen: fix warnings from GCC 5.4's -Wall -Wextra

Psychtoolbox/PsychHardware/XOrgConfCreator.m
XOrgConfCreator fails on my machine due to the fact it uses && logic with strfind, but strfind does not return logical values. One can either use & to bypass the logical requirement or wrap strfind using ~isempty() which I did here...
=> Fix XOrgConfCreator.m: make sure strfind returns logical result

Psychtoolbox/PsychOneliners/Ask.m
Since PTB-3 the text automatically aligns by the top of the text because
the 'yPositionIsBaseline' argument defaults to 0. By hardcoding it to 1
in the Ask.m function the text aligns to the bottom again.
=> Ask.m update - align text

Psychtoolbox/PsychOpenGL/LoadOBJFile.m
% do some change here to prevent there no exists normal or texture coordinates    
objobject{meshcount}.normals = Normals(:, 1:vnnum);  %#ok<AGROW> 
objobject{meshcount}.texcoords = Texcoords(:, 1:vtnum);  %#ok<AGROW>
=> LoadOBJFile: Fix error if texture coordinates or normal vectors are missing

PsychSourceGL/Source/Common/PsychPortAudio/PsychPortAudio.c
Master code was writing to outputBuffer without checking it first. Check for NULL pointer before writing to outputBuffer in master control logic within paCallback.
=> Fix segfault after PsychPortAudio starts Master Capture device

PsychSourceGL/Source/Common/PsychPortAudio/PsychPortAudio.c
There is a simple case where PsychPortAudio could overwrite its audiodevice registry due to a bad handle.
1. PsychPortAudio('Open', ...) -> handle = 0, audiodevicecount = 1
2. PsychPortAudio('Open', ...) -> handle = 1, audiodevicecount = 2
3. PsychPortAudio('Close', 0) -> audiodevicecount = 1
4. PsychPortAudio('Open', ...) -> handle = 1, audiodevicecount = 2
At the end of this sequence, we have two streams, established in steps 2 and 4 that are identified by handle 1. In fact handle 1 only points to the stream created in 4. It was overwritten.
Proposed fix uses adds a small utility function nextHandle that returns the index of the first unused audiodevices slot.
=> PsychPortAudio handle lifecyle issue

Psychtoolbox/PsychDemos/Contents.m, Psychtoolbox/PsychDemos/ProceduralSmoothedDiscMaskDemo.m, Psychtoolbox/PsychDemos/ProceduralSmoothedDiscsDemo.m, Psychtoolbox/PsychGLImageProcessing/CreateProceduralSmoothedDisc.m, Psychtoolbox/PsychOpenGL/PsychGLSLShaders/SmoothedDiscShader.frag.txt, Psychtoolbox/PsychOpenGL/PsychGLSLShaders/SmoothedDiscShader.vert.txt
This commit just allow a user to pass an alpha value per disc when using DrawTextures. Update the demo to "pulse" the alpha values for each disc. A few doc fixes and use ~KbCheck instead of fixed timer.
=> ProceduralSmoothedDiscs per-disc alpha parameter added

managementtools/PTB-wikify-into-files.py
This function supports exporting ptb help text into formatted files.  These can be used to directly add into a github wiki repository, or github pages repository (note github pages need config setting: permalink:  /:title.html)
Also since these are formatted files they can be adapted to different formats using  pandoc (e.g. html) and that can support using various other platforms.  
It's not obvious what platform is the best for hosting going forward one is best
Problem:
The GitHub Wiki platform cannot hold a dump of all the files.  Specifically the PsychOpenGL folder has many files in it. When these are included the GitHub wiki starts throwing rendering took to long errors on pages with more than ~20 links. 
The GitHub Pages platform also throws a build time error timeout when trying to …
=> Code to help migrate Psychtoolbox help onto GitHub Wiki

Psychtoolbox/UpdatePsychtoolbox.m
I often run UpdatePsychtoolbox when MATLAB does not have Psychtoolbox in its path. UpdatePsychtoolbox sets up the path correctly. However, to run, UpdatePsychtoolbox needs to use 
Psychtoolbox/PsychOneliners/PsychRoot.m
so this change adds the PsychOneliners folder to the path, assuming that UpdatePsychtoolbox is in the Psychtoolbox folder. It not, this generates a harmless warning.
=> add PsychOneliners folder to path.

PsychSourceGL/Source/Common/Screen/PsychImagingPipelineSupport.c, PsychSourceGL/Source/Common/Screen/PsychWindowSupport.c, PsychSourceGL/Source/Common/Screen/PsychWindowSupport.h, PsychSourceGL/Source/Common/Screen/SCREENGetImage.c, PsychSourceGL/Source/Common/Screen/SCREENGetWindowInfo.c, PsychSourceGL/Source/Common/Screen/SCREENOpenWindow.c, PsychSourceGL/Source/Common/Screen/ScreenTypes.h, PsychSourceGL/Source/Common/Screen/WindowBank.h, PsychSourceGL/Source/Linux/Screen/PsychWindowGlue.c, PsychSourceGL/Source/OSX/Screen/PsychWindowGlue.c, PsychSourceGL/Source/Windows/Screen/PsychWindowGlue.c, Psychtoolbox/PsychGLImageProcessing/PsychImaging.m, Psychtoolbox/PsychTests/VRRTest.m
Add a new VRR mode, mode 3 (aka "OwnScheduled"). It can be passed as
mode 3 for the vrrParams=[mode, styleHint, minDuration, maxDuration]
argument vector to Screen('OpenWindow', ..., vrrParams);
Or preferrably it can be requested via a call to:
PsychImaging('AddTask', 'General', 'UseFineGrainedTiming', 'OwnScheduled');
In the current implementation, mode 3 / 'OwnScheduled' gets also
selected as current best default choice if mode 1 is selected in
Screen('OpenWindow') or 'Auto' is specified in PsychImaging via
PsychImaging('AddTask', 'General', 'UseFineGrainedTiming', 'Auto');
The difference to mode 2 / 'Simple' is that we don't simply wait
until the Screen('Flip', window, when); 'when' deadline and then
call glXSwapBuffers() to request a buffer swap at 'when' (or call
glXSwapBuffers() …
=> Screen/Linux: Add our own custom VRR scheduler.

Psychtoolbox/PsychDemos/ProceduralGarboriumDemo.m
Without Priority, my Radeon Pro WX 5100 can do around 6000 gabors before it starts dropping frames at 60Hz. With Priority that goes up to ~7800, a significant increase. It seems worth adding for this demo. Some other small clean-up (consistent preallocation etc.)
=> Add priority to ProceduralGarboriumDemo

Psychtoolbox/PsychBasic/PsychtoolboxVersion.m
See #189. The offending java call is now wrapped in a try ... catch so that . In addition, I've added support for git or manual installs. git support uses the existing GetGITInfo() function from PTB. The code checks for a `.git` or a `.svn` folder and the current checking order is:
1. test neurodebian 
2. test for git folder
3. test no svn folder
4. assume svn
If you don't want to make too many changes you can just cherry-pick the try ... catch bit and reject the other parts, or I can rewrite the pull as you prefer.
=> PsychtoolboxVersion: add support for git and manual install methods

Psychtoolbox/PsychDocumentation/BeampositionQueries.m, Psychtoolbox/PsychDocumentation/ConserveVRAMSettings.m, Psychtoolbox/PsychDocumentation/DisplayOutputMappings.m, Psychtoolbox/PsychDocumentation/DrawTextEncodingLocaleSettings.m, Psychtoolbox/PsychDocumentation/HybridGraphics.m, Psychtoolbox/PsychDocumentation/InstallKinect.m, Psychtoolbox/PsychDocumentation/KbQueue.html, Psychtoolbox/PsychDocumentation/LinuxGameMode.m, Psychtoolbox/PsychDocumentation/ProceduralShadingAPI.m, Psychtoolbox/PsychDocumentation/ProgrammingTips.html, Psychtoolbox/PsychDocumentation/PsychPaidSupportAndServices.m, Psychtoolbox/PsychDocumentation/RaspberryPiSetup.m, Psychtoolbox/PsychDocumentation/SyncTrouble.m, Psychtoolbox/PsychDocumentation/VideoRecording.m, managementtools/Logonotes.txt, managementtools/PTB-wikify-into-files.py, managementtools/PTB-wikify.py, managementtools/parseptblog.php
This patch restricts itself to the following folders and fixes 54 out of 3552 reported typos (some of which might be false positives of course):
* `Psychtoolbox/PsychDocumentation`
* `managementtools`
Would you be willing to accept further fixes of typos found by [codespell](https://github.com/codespell-project/codespell)?
=> Typos found by codespell

PsychPython/psychtoolbox/audio.py, PsychPython/psychtoolbox/hid.py
This is an error reported by LGTM.com:
https://lgtm.com/projects/g/kleinerm/Psychtoolbox-3/?severity=error
I'm not certain whether Psychtoolbox still supports Python 2 or only Python 3. Either way:
* In Python 2 both class `OldStyle` and class `OldStyle()` define "old-style" classes and `@property` requires new-style classes.
* Python 3 provides "new-style" classes only, so if only Python 3 is supported, this would be a false positive. I believe using Python 3 definitions (without parenthesis for inheritance) will make clear this a Python 3 definition and the alert will disappear.
=> Property will not work properly, as class Stream is an old-style class

Psychtoolbox/PsychFiles/PsychtoolboxConfigDir.m
This change is due to a MATLAB Compiler error due to the use of
`unix('echo $HOME')` whereas `getenv('HOME')` compiles OK (only tested on macOS so
far) -- note that both MATLAB and Octave support the use of `getenv()`. Once compiled and run, `getenv('HOME')` correctly retrieves the user's home dir just fine...
This is simplified from the previous pull #219 (no need to use `isdeployed`) with a more descriptive title (hope it's OK)...
=> PsychtoolboxConfigDir(): Use getenv('HOME') to retrieve home directory instead of unix('echo $HOME')

Psychtoolbox/PsychFiles/PsychHomeDir.m
Update the unix('echo $HOME') code to use getenv('HOME') as this is
possibly less fragile and is supported on Octave and MATLAB. THe
codepath for macOS and Linux was the same so I merged them, and just in
case the path doesn't end in filesep before joining to subDir we test
and add if necessary...
See #221
=> PsychHomeDir(): use getenv('HOME')

Psychtoolbox/PsychOneliners/AssertOpenGL.m
Only use it if user opted in via setenv('PSYCH_ALLOW_WAYLAND', '1').
Use by default on Octave + Linux was a bad idea, as it would expose users who logged into a
Wayland session accidentally to a half-finished backend on a unsuitable display server. This
would happen, e.g., to all Ubuntu 22.04-LTS users by default if they used Octave!
=> AssertOpenGL(): Do not use Wayland backend by default.

PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.c, setup.py
Hi Mario,
I'm cautiously optimistic this fixes the weak linking of libusb introduced in 26ebaae94b4dfb481fa3a928931d80dfa138d646 (all of the "real" Macs I have access to walked away for the day before I got to test). Here's what the original commit gave me: 
https://github.com/aforren1/ptb-wheels/actions/runs/4116377822/jobs/7106352950#step:5:486
and here's one of the successful ones following the change:
https://github.com/aforren1/ptb-wheels/actions/runs/4118809478/jobs/7111777645#step:5:1146
I should get to test locally sometime tomorrow? If you wanted to peek at the wheels, they're all available under the "Artifacts" section here: https://github.com/aforren1/ptb-wheels/actions/runs/4118809478
I also worked in a fix for GCC-related detection, which would incorrectly error if Clang was …
=> Python fixes for weakly linking libusb & compiler detection

MANIFEST.in
This change tells Python to include the necessary shared & static libraries for building PsychPortAudio/PsychHID in the source archive. If the entrepreneurial user tried to install from source instead of relying on one of the pre-built wheels, the build step would fail due to these missing dependencies.
I now test building from the source archive on Linux/Win/Mac, and appears successful (see e.g. [here](https://github.com/aforren1/ptb-wheels/actions/runs/4448339211)).
Originally reported by Ian [here](https://psychtoolbox.discourse.group/t/libusb-and-the-psychtoolbox-wheel-in-psychopy/4883).
=> Python: include Windows & Mac build- and run-time dependencies in the source distribution

.github/workflows/buildZipMLTBX.yml, .github/workflows/buildZipMLTBXReleaseDriven.yml
The tag driven action for releasing zip/ MLTBX is modified with the following changes:
1.	The Action is now release driven meaning it will executed once you publish a release
2.	It will only update the last published release with zip and MLTBX artifacts
The action is implemented in the file buildZipMLTBXReleaseDriven.yml. I have modified the original workflow file (buildZipMLTBX.yml) to be manually triggered to prevent it from executing when a tag is pushed.
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, …
=> Updates to the GH Action for building and releasing zip/ MLTBX artifacts

Psychtoolbox/PsychOneliners/GetGitPath.m
'where git' returns the path including 'git.exe', and `GetGITInfo()` only expects the path minus the executable. This chops the 'git.exe' off.
Successfully tested on Win11 + git from https://www.git-scm.com/. Originally, it would fail at the `git describe` step because the concatenated command was '"C:\Program Files\Git\cmd\git.exe"git'.
Unrelated, but any reason the Mac/Linux branch of `GetGITInfo()` couldn't be replaced with `which git` instead of checking predefined paths?
=> GetGitPath(): Fix path to git on MS-Windows.

PsychSourceGL/Source/Common/Screen/SCREENDrawDots.c
Only round dots get trimmed in the fragment shader, and so dot_type=4 was left with too much padding from the vertex shader.
Tested on Ubuntu 20.04 + AMD Pro W5500 + Octave with this script: https://gist.github.com/aforren1/31028d18da246db26bae207a009d23b0. The first row of dots is `dot_type=0`, the second row is `dot_type=4`, and the third is `dot_type=3`.
The first image is the old behavior with 10px dots, and the second is the new.
=> Screen('DrawDots'): Only apply a margin to non-square dot types.

PsychSourceGL/Source/Common/Base/PythonGlue/PsychScriptingGluePython.c, pyproject.toml, setup.py
1. Add a content type for the description in `setup.py`, without it `twine check --strict` complains.
2. Build against NumPy 2.0 in the `build-system` when possible (i.e., on Python 3.9 or later). This will create code that is compatible with both NumPy 1.x and 2.x.
3. Replace `PyArray_REFCOUNT` with the drop-in replacement `Py_REFCNT` (the former is gone in NumPy 2.0)
The first commit is the content-type fix. The next commit contains the two changes that make things compatible with NumPy 2.0, done following suggestions in their [release notes](https://numpy.org/devdocs/release/2.0.0-notes.html).
I've tested that the wheels produced using this branch work on Linux as well in https://github.com/aforren1/ptb-wheels/pull/10.
=> Fixes for NumPy 2.0
